[user]
name = "Sean McArthur"
email = "sean@seanmonstar.com"

[ui]
default-command = ["log"]
editor = "vim"

[git]
# what do I do to replicate this behavior? I don't want to auto track
# other people's bookmarks. Feels like a step backwards...
# push-new-bookmarks = true
git_push_bookmark = '"sean/" ++ change_id.short()'

[revset-aliases]
'unreleased' = 'heads(::@ & tags())::@'

[aliases]
d = ["diff"]
f = ["git", "fetch"]
s = ["status"]

re = ["rebase", "-d"]
remaster = ["rebase", "--onto", "trunk()", "-r"]

unreleased = ["log", "-r", "unreleased"]
ll = ["log", "-r", "ancestors(@, 10)"]

init = ["git", "init", "--colocate"]

[template-aliases]
shortlog = '''
  if(root,
    format_root_commit(self),
    label(if(current_working_copy, "working_copy"),
      concat(
        separate(" ",
          format_short_change_id_with_hidden_and_divergent_info(self),
          if(empty, label("empty", "(empty)")),
          if(description,
            description.first_line(),
            label(if(empty, "empty"), description_placeholder),
          ),
          bookmarks,
          tags,
          working_copies,
          if(git_head, label("git_head", "HEAD")),
          if(conflict, label("conflict", "conflict")),
          if(config("ui.show-cryptographic-signatures").as_boolean(),
            format_short_cryptographic_signature(signature)),
        ) ++ "\n",
      ),
    )
  )
'''
